# Header
links:
  - name: about
    url: http://daiyi.co
  - name: by topic
    url: http://daiyi.co/blog/archives
  - name: rss
    url: http://daiyi.co/blog/rss2.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png

frontmatter_comments:
  color: "#3EF5DB"
  repo_root: https://github.com/daiyitastic/blog/blob/master/source/_posts/
  default:
    - name: daiyi
      url: http://daiyi.co
      comment: No comments at the moment \o/ Hey you can write one! It will make me so happy.
