# Header
links:
  - name: about
    url: http://daiyi.co
  - name: by topic
    url: http://daiyi.co/blog/archives
  - name: rss
    url: http://daiyi.co/blog/rss2.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: daiyitastic

markdown_comments:
  repo_root: https://github.com/daiyi/blog/blob/master/source/_posts/
